Name:           ros-kinetic-vs060-moveit-config
Version:        2.0.2
Release:        0%{?dist}
Summary:        ROS vs060_moveit_config package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/vs060_moveit_config
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-moveit-planners-ompl
Requires:       ros-kinetic-moveit-ros-move-group
Requires:       ros-kinetic-moveit-ros-visualization
Requires:       ros-kinetic-moveit-simple-controller-manager
Requires:       ros-kinetic-robot-state-publisher
Requires:       ros-kinetic-vs060
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-moveit-planners-ompl
BuildRequires:  ros-kinetic-moveit-ros-move-group
BuildRequires:  ros-kinetic-moveit-ros-visualization
BuildRequires:  ros-kinetic-moveit-simple-controller-manager
BuildRequires:  ros-kinetic-robot-state-publisher

%description
An automatically generated package with all the configuration and launch files
for using the vs060A1_AV6_NNN_NNN with the MoveIt Motion Planning Framework

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Wed Nov 01 2017 Ryohei Ueda <ueda@jsk.t.u-tokyo.ac.jp> - 2.0.2-0
- Autogenerated by Bloom

* Wed Aug 09 2017 Ryohei Ueda <ueda@jsk.t.u-tokyo.ac.jp> - 2.0.1-0
- Autogenerated by Bloom

