Name:           ros-hydro-vs060-moveit-config
Version:        0.2.8
Release:        0%{?dist}
Summary:        ROS vs060_moveit_config package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/vs060_moveit_config
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-moveit-planners-ompl
Requires:       ros-hydro-moveit-ros-move-group
Requires:       ros-hydro-moveit-ros-visualization
Requires:       ros-hydro-pr2-moveit-plugins
Requires:       ros-hydro-robot-mechanism-controllers
Requires:       ros-hydro-robot-state-publisher
Requires:       ros-hydro-vs060
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-moveit-planners-ompl
BuildRequires:  ros-hydro-moveit-ros-move-group
BuildRequires:  ros-hydro-moveit-ros-visualization
BuildRequires:  ros-hydro-pr2-moveit-plugins
BuildRequires:  ros-hydro-robot-mechanism-controllers
BuildRequires:  ros-hydro-robot-state-publisher

%description
An automatically generated package with all the configuration and launch files
for using the vs060A1_AV6_NNN_NNN with the MoveIt Motion Planning Framework

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Wed Jul 30 2014 Ryohei Ueda <ueda@jsk.t.u-tokyo.ac.jp> - 0.2.8-0
- Autogenerated by Bloom

