joint_limits:
  flange:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: true
    max_acceleration: 0.7
  j1:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: true
    max_acceleration: 0.7
  j2:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: true
    max_acceleration: 0.7
  j3:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: true
    max_acceleration: 0.7
  j4:
    has_velocity_limits: true
    max_velocity: 0.4
    has_acceleration_limits: true
    max_acceleration: 0.5
  j5:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: true
    max_acceleration: 0.7
    